---
- name: Ping Localhost
  hosts: localhost
  connection: local

  tasks:
    - name: Sleep
      ansible.builtin.pause:
        seconds: 10
    - name: Test connection
      ansible.builtin.ping:
...
